version: "3.1"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: airbnb_user
      POSTGRES_PASSWORD: airbnb_password
      POSTGRES_DB: airbnb_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
